version : '3.8'
services:
  automotive-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: automotive
    networks:
      - ngusa
networks:
  ngusa:
